import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api, ApiError } from '../api/client';
import { useAuth } from '../auth';
import { Loading, Notice } from '../components/Layout';
import type { Event, TicketType } from '../types/api';

const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : 'Unable to reach the API. Please try again.';

export function OrganizerDashboard() {
  const { session } = useAuth(); const [events, setEvents] = useState<Event[]>([]); const [name, setName] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = () => api.myEvents(session!.token).then(setEvents).catch(e => setError(errorMessage(e))).finally(() => setLoading(false));
  useEffect(() => { load(); }, [session]);
  async function create(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); try { const event = await api.createEvent(name, session!.token); setEvents(items => [...items, event]); setName(''); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  return <><div className="page-heading"><div><p className="eyebrow">Organizer workspace</p><h1>Your events</h1><p className="muted">Create an event, then add ticket types and track available inventory.</p></div></div><section className="create-panel"><h2>Create an event</h2><form className="inline-form" onSubmit={create}><input placeholder="Event name" value={name} onChange={e => setName(e.target.value)} required /><button disabled={busy}>{busy ? 'Creating…' : 'Create event'}</button></form></section>{error && <Notice>{error}</Notice>}{loading ? <Loading /> : events.length === 0 ? <div className="empty">You have not created an event yet.</div> : <div className="card-grid">{events.map(event => <article className="card" key={event.id}><p className="eyebrow">Your event</p><h2>{event.name}</h2><p className="muted">Manage ticket types, availability, or event details.</p><Link className="button" to={`/organizer/events/${event.id}`}>Manage event</Link></article>)}</div>}</>;
}

export function ManageEvent() {
  const { id = '' } = useParams(); const { session } = useAuth(); const navigate = useNavigate(); const [event, setEvent] = useState<Event | null>(null); const [tickets, setTickets] = useState<TicketType[]>([]); const [name, setName] = useState(''); const [ticketName, setTicketName] = useState(''); const [price, setPrice] = useState(''); const [totalQuantity, setTotalQuantity] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([api.myEvents(session!.token), api.ticketTypes(id)]).then(([ownEvents, ticketTypes]) => { const own = ownEvents.find(item => String(item.id) === id); if (!own) throw new ApiError('You can only manage your own events.', 403); setEvent(own); setName(own.name); setTickets(ticketTypes); }).catch(e => setError(errorMessage(e))).finally(() => setLoading(false)); }, [id, session]);
  async function update(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { setEvent(await api.updateEvent(id, name, session!.token)); setSuccess('Event name updated.'); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  async function addTicket(e: FormEvent) { e.preventDefault(); setBusy(true); setError(''); setSuccess(''); try { const ticket = await api.createTicketType(id, { name: ticketName, price: Number(price), totalQuantity: Number(totalQuantity) }, session!.token); setTickets(items => [...items, ticket]); setTicketName(''); setPrice(''); setTotalQuantity(''); setSuccess('Ticket type created.'); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  async function remove() { if (!window.confirm('Delete this event? Events with ticket types cannot be deleted.')) return; setBusy(true); setError(''); try { await api.deleteEvent(id, session!.token); navigate('/organizer'); } catch (err) { setError(errorMessage(err)); } finally { setBusy(false); } }
  if (loading) return <Loading />;
  if (!event) return <><Notice>{error || 'Event not found.'}</Notice><Link to="/organizer">Back to my events</Link></>;
  return <><Link className="back-link" to="/organizer">← My events</Link><div className="page-heading"><div><p className="eyebrow">Manage event</p><h1>{event.name}</h1></div><button className="danger" disabled={busy} onClick={remove}>Delete event</button></div>{error && <Notice>{error}</Notice>}{success && <Notice kind="success">{success}</Notice>}<div className="two-columns"><section className="create-panel"><h2>Event details</h2><form onSubmit={update}><label>Event name<input value={name} onChange={e => setName(e.target.value)} required /></label><button disabled={busy}>Save changes</button></form></section><section className="create-panel"><h2>Add ticket type</h2><form onSubmit={addTicket}><label>Name<input value={ticketName} onChange={e => setTicketName(e.target.value)} required /></label><label>Price<input type="number" min="0" step="1" value={price} onChange={e => setPrice(e.target.value)} required /></label><label>Total quantity<input type="number" min="1" step="1" value={totalQuantity} onChange={e => setTotalQuantity(e.target.value)} required /></label><button disabled={busy}>Add ticket type</button></form></section></div><section><div className="section-heading"><h2>Inventory</h2><p className="muted">Available tickets update as customers reserve or buy.</p></div>{tickets.length === 0 ? <div className="empty">Add your first ticket type to start selling.</div> : <div className="ticket-list">{tickets.map(ticket => <article className="ticket-row" key={ticket.id}><div><h2>{ticket.name}</h2><p className="muted">Total: {ticket.totalQuantity} · Available: {ticket.availableQuantity}</p></div><strong>₹{ticket.price}</strong></article>)}</div>}</section></>;
}
